
services:
  frontend:
    build:
      context: ./  
    image: 'frontend-app'
    ports:
      - '5173:5173'
    volumes:
      - './:/app'
      - /app/node_modules
    environment:
      VITE_API_URL: '${VITE_API_BASE_URL:-http://127.0.0.1:8080/api/tasks}'

